def my_func(x):
    try:
        sum = x + 1 

    except Exception as e:
        print("Error: ", e) 

my_func("Sinem")
